# Python tips to HELP YOU

## Reminder: review the last assessment's solutions!

### dict.get() will keep you from getting key errors

In [1]:
d = {8:'jerri', 0:'jellineck', 3:'joffrey'}

In [2]:
d[8]

'jerri'

In [3]:
d[1]

KeyError: 1

In [4]:
d.get?

In [5]:
d.get(1,'blank')

'blank'

In [6]:
d.get(1, [])

[]

In [7]:
d

{0: 'jellineck', 3: 'joffrey', 8: 'jerri'}

In [8]:
d['grape'] = 30

In [9]:
d

{0: 'jellineck', 3: 'joffrey', 8: 'jerri', 'grape': 30}

## Numpy tips

In [10]:
import numpy as np

### Slicing & Indexing

slicing notation: `[start:stop:step]`

In [11]:
foo = np.random.randint(30, size=(20))
print foo
print foo.shape

[ 3 26 13  8 12 16  9  4  2  7 21 10 15  4 27 25 28 11 28  3]
(20,)


Get the first five elements:

In [12]:
foo[:5]

array([ 3, 26, 13,  8, 12])

Get the last five elements:

In [13]:
foo[-5:]

array([25, 28, 11, 28,  3])

Get every other element, starting with the first:

In [14]:
foo[::2]

array([ 3, 13, 12,  9,  2, 21, 15, 27, 28, 28])

In [15]:
foo[::-2]

array([ 3, 11, 25,  4, 10,  7,  4, 16,  8, 26])

Get the twelfth element five times:

(Hint: you can index a numpy array with a list)

In [16]:
list_mask = [11,11,11,11,11]
foo[list_mask]

array([10, 10, 10, 10, 10])

Wow! Indexing a NUMPY ARRAY with a LIST OF INTS works great! 

In [17]:
list_mask_2 = [1, 6, 1, 0, 1, 3]
foo[list_mask_2]

array([26,  9, 26,  3, 26,  8])

In [18]:
list_mask_3 = [1, 26, 1, 0, 1, 3]
foo[list_mask_3]

IndexError: index 26 is out of bounds for axis 1 with size 20